export const offboardingFormSchema = {
  slug: "employee-offboarding",
  title: "Employee Offboarding Request",
  description: "Submit an employee offboarding request for IT deprovisioning.",
  sections: [
    {
      id: "employee_info",
      title: "Employee Information",
      fields: [
        { id: "first_name", type: "text", label: "First Name", required: true },
        { id: "last_name", type: "text", label: "Last Name", required: true },
        { id: "company_email", type: "email", label: "Company Email", required: true },
        { id: "job_title", type: "text", label: "Job Title", required: true },
        {
          id: "department",
          type: "select",
          label: "Department",
          required: true,
          options: [
            { value: "rnd", label: "R&D" },
            { value: "marketing", label: "Marketing" },
            { value: "hr", label: "HR" },
            { value: "bizdev", label: "Biz Dev & Strategy" },
            { value: "finance", label: "Finance" },
            { value: "operations", label: "Operations" },
            { value: "legal", label: "Legal" },
            { value: "it", label: "IT" },
            { value: "other", label: "Other" },
          ],
        },
        { id: "office_location", type: "text", label: "Office Location", required: false },
      ],
    },
    {
      id: "termination",
      title: "Termination Details",
      fields: [
        {
          id: "termination_type",
          type: "select",
          label: "Termination Type",
          required: true,
          options: [
            { value: "voluntary", label: "Voluntary (Resignation)" },
            { value: "involuntary", label: "Involuntary (Termination)" },
            { value: "end_of_contract", label: "End of Contract / Internship" },
            { value: "retirement", label: "Retirement" },
            { value: "mutual", label: "Mutual Separation" },
          ],
        },
        { id: "last_working_day", type: "date", label: "Last Working Day", required: true },
        { id: "termination_effective_date", type: "date", label: "Termination Effective Date", required: true },
        { id: "immediate_disable", type: "checkbox", label: "Immediate Account Disable Required", required: false, helperText: "Auto-enabled for involuntary terminations" },
        { id: "supervisor_name", type: "text", label: "Manager / Supervisor", required: true },
        { id: "supervisor_email", type: "email", label: "Manager Email", required: true },
        { id: "hr_contact_email", type: "email", label: "HR Contact Email", required: true },
        {
          id: "rehire_eligible",
          type: "select",
          label: "Rehire Eligible",
          required: false,
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
            { value: "tbd", label: "TBD" },
          ],
        },
      ],
    },
    {
      id: "data_handover",
      title: "Data Ownership & Handover",
      fields: [
        {
          id: "mailbox_action",
          type: "select",
          label: "Email Mailbox Action",
          required: true,
          options: [
            { value: "disable_immediately", label: "Disable Immediately" },
            { value: "forward", label: "Forward to Another User" },
            { value: "shared_mailbox", label: "Convert to Shared Mailbox" },
            { value: "retain", label: "Retain for X Days" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "forwarding_recipient",
          type: "email",
          label: "Forwarding Recipient Email",
          required: false,
          condition: { field: "mailbox_action", value: "forward" },
        },
        {
          id: "retention_days",
          type: "number",
          label: "Retention Duration (days)",
          required: false,
          condition: { field: "mailbox_action", value: "retain" },
        },
        {
          id: "onedrive_action",
          type: "select",
          label: "OneDrive Action",
          required: true,
          options: [
            { value: "transfer_manager", label: "Transfer to Manager" },
            { value: "transfer_other", label: "Transfer to Another User" },
            { value: "retain", label: "Retain for Review" },
            { value: "delete", label: "Delete" },
          ],
        },
        {
          id: "onedrive_recipient",
          type: "email",
          label: "OneDrive Transfer Recipient",
          required: false,
          condition: { field: "onedrive_action", value: "transfer_other" },
        },
        { id: "shared_folders", type: "textarea", label: "Shared Folders Handover Notes", required: false },
        { id: "project_files", type: "textarea", label: "Project Files Handover Notes", required: false },
        { id: "external_accounts", type: "textarea", label: "External Accounts to Transfer", required: false, helperText: "Vendor portals, social media, etc." },
        { id: "shared_credentials", type: "textarea", label: "Shared Credentials to Review", required: false, helperText: "Any shared accounts this person had access to" },
      ],
    },
    {
      id: "compliance",
      title: "Compliance, Legal & Risk",
      fields: [
        { id: "legal_hold", type: "checkbox", label: "Legal Hold Required", required: false },
        {
          id: "legal_hold_details",
          type: "textarea",
          label: "Legal Hold Details",
          required: false,
          condition: { field: "legal_hold", value: true },
        },
        {
          id: "regulatory_requirements",
          type: "multiselect",
          label: "Regulatory Requirements",
          required: false,
          options: [
            { value: "gdpr", label: "GDPR" },
            { value: "sox", label: "SOX" },
            { value: "hipaa", label: "HIPAA" },
            { value: "pci_dss", label: "PCI-DSS" },
            { value: "none", label: "None" },
          ],
        },
        { id: "customer_access", type: "checkbox", label: "Customer / Partner Access Involved", required: false },
        { id: "privileged_account", type: "checkbox", label: "Privileged Account Holder (Admin Access)", required: false },
        { id: "high_risk", type: "checkbox", label: "High-Risk Departure (HR Flag)", required: false },
        { id: "security_incident", type: "checkbox", label: "Security Incident / Investigation", required: false },
        { id: "known_owned_systems", type: "textarea", label: "Known Owned Systems", required: false, helperText: "Systems where this person is primary admin/owner" },
      ],
    },
    {
      id: "asset_recovery",
      title: "Asset Recovery",
      fields: [
        { id: "device_return_required", type: "checkbox", label: "Device Return Required", required: false },
        {
          id: "device_return_method",
          type: "select",
          label: "Device Return Method",
          required: false,
          condition: { field: "device_return_required", value: true },
          options: [
            { value: "in_office", label: "In-Office Return" },
            { value: "shipping_label", label: "Shipping Label Provided" },
            { value: "on_site_pickup", label: "On-Site Pickup" },
          ],
        },
        {
          id: "shipping_address",
          type: "textarea",
          label: "Shipping Address for Return Label",
          required: false,
          condition: { field: "device_return_method", value: "shipping_label" },
        },
      ],
    },
  ],
} as const;
