export const onboardingFormSchema = {
  slug: "employee-onboarding",
  title: "Employee Onboarding Request",
  description: "Submit a new employee onboarding request for IT provisioning.",
  sections: [
    {
      id: "employee_info",
      title: "Employee Information",
      fields: [
        { id: "first_name", type: "text", label: "First Name", required: true },
        { id: "last_name", type: "text", label: "Last Name", required: true },
        { id: "personal_email", type: "email", label: "Personal Email", required: true, helperText: "Pre-employment communication" },
        { id: "personal_phone", type: "tel", label: "Personal Phone", required: true },
        { id: "job_title", type: "text", label: "Job Title", required: true },
        {
          id: "department",
          type: "select",
          label: "Department",
          required: true,
          options: [
            { value: "rnd", label: "R&D" },
            { value: "marketing", label: "Marketing" },
            { value: "hr", label: "HR" },
            { value: "bizdev", label: "Biz Dev & Strategy" },
            { value: "finance", label: "Finance" },
            { value: "operations", label: "Operations" },
            { value: "legal", label: "Legal" },
            { value: "it", label: "IT" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "employment_type",
          type: "select",
          label: "Employment Type",
          required: true,
          options: [
            { value: "full_time", label: "Full-Time Employee" },
            { value: "part_time", label: "Part-Time Employee" },
            { value: "contractor", label: "Contractor" },
            { value: "intern", label: "Intern" },
          ],
        },
        { id: "legal_entity", type: "text", label: "Legal Entity / Company", required: true, defaultValue: "Zimark Inc." },
        { id: "cost_center", type: "text", label: "Cost Center", required: false },
        {
          id: "office_location",
          type: "select",
          label: "Office Location",
          required: true,
          options: [
            { value: "hq", label: "HQ" },
            { value: "remote", label: "Remote" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "time_zone",
          type: "select",
          label: "Time Zone",
          required: true,
          options: [
            { value: "America/New_York", label: "Eastern (ET)" },
            { value: "America/Chicago", label: "Central (CT)" },
            { value: "America/Denver", label: "Mountain (MT)" },
            { value: "America/Los_Angeles", label: "Pacific (PT)" },
            { value: "Europe/London", label: "GMT/BST" },
            { value: "Europe/Berlin", label: "CET" },
            { value: "Asia/Jerusalem", label: "IST (Israel)" },
            { value: "other", label: "Other" },
          ],
        },
        { id: "start_date", type: "date", label: "Start Date", required: true },
        { id: "vip_flag", type: "checkbox", label: "VIP / Expedited", required: false },
      ],
    },
    {
      id: "reporting",
      title: "Reporting & Approvals",
      fields: [
        { id: "supervisor_name", type: "text", label: "Supervisor / Manager Name", required: true },
        { id: "supervisor_email", type: "email", label: "Manager Email", required: true },
        { id: "hr_contact_email", type: "email", label: "HR Contact Email", required: false },
        { id: "budget_approver_email", type: "email", label: "Budget Approver Email", required: false, helperText: "Defaults to manager if blank" },
      ],
    },
    {
      id: "access_profile",
      title: "Access & Role Profile",
      fields: [
        {
          id: "role_template",
          type: "select",
          label: "Access Profile / Role Template",
          required: false,
          options: [
            { value: "engineering_standard", label: "Engineering Standard" },
            { value: "marketing_standard", label: "Marketing Standard" },
            { value: "hr_standard", label: "HR Standard" },
            { value: "bizdev_standard", label: "BizDev Standard" },
            { value: "executive", label: "Executive" },
            { value: "contractor_limited", label: "Contractor Limited" },
            { value: "intern", label: "Intern" },
            { value: "custom", label: "Custom" },
          ],
        },
        {
          id: "additional_apps",
          type: "multiselect",
          label: "Additional Applications",
          required: false,
          options: [
            { value: "slack", label: "Slack" },
            { value: "microsoft_365", label: "Microsoft 365" },
            { value: "notion", label: "Notion" },
            { value: "aws_vpn_client", label: "AWS VPN Client" },
            { value: "sentinelone", label: "SentinelOne" },
            { value: "rustdesk", label: "RustDesk" },
            { value: "teamviewer", label: "TeamViewer" },
            { value: "putty", label: "Putty" },
            { value: "vscode", label: "VS Code" },
            { value: "git", label: "Git" },
            { value: "other", label: "Other" },
          ],
        },
        { id: "aws_access_required", type: "checkbox", label: "AWS Access Required", required: false },
        {
          id: "aws_role",
          type: "select",
          label: "AWS Role / Permission Set",
          required: false,
          condition: { field: "aws_access_required", value: true },
          options: [
            { value: "developer_read", label: "Developer (Read Only)" },
            { value: "developer_rw", label: "Developer (Read-Write)" },
            { value: "admin", label: "Admin" },
            { value: "billing_read", label: "Billing (Read Only)" },
          ],
        },
        { id: "vpn_access", type: "checkbox", label: "VPN Access Required", required: false },
      ],
    },
    {
      id: "device_hardware",
      title: "Device & Hardware",
      fields: [
        {
          id: "kit_type",
          type: "select",
          label: "Kit Type",
          required: true,
          options: [
            { value: "dell_latitude", label: "Dell Latitude Kit" },
            { value: "lenovo_thinkpad", label: "Lenovo ThinkPad Kit" },
            { value: "macbook_air", label: "Apple MacBook Air Kit" },
            { value: "macbook_pro", label: "Apple MacBook Pro Kit" },
            { value: "macbook_pro_max", label: "Apple MacBook Pro Max Kit" },
            { value: "none", label: "No Device Needed" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "peripherals",
          type: "multiselect",
          label: "Peripherals",
          required: false,
          options: [
            { value: "headphones_mic", label: "Headphones (with microphone)" },
            { value: "monitor", label: "External Monitor" },
            { value: "keyboard", label: "Keyboard" },
            { value: "mouse", label: "Mouse" },
            { value: "docking_station", label: "Docking Station" },
            { value: "webcam", label: "Webcam" },
            { value: "other", label: "Other" },
          ],
        },
        { id: "device_shipping", type: "checkbox", label: "Device Shipping Required", required: false },
        {
          id: "shipping_address",
          type: "textarea",
          label: "Shipping Address",
          required: false,
          condition: { field: "device_shipping", value: true },
        },
        {
          id: "shipping_priority",
          type: "select",
          label: "Shipping Priority",
          required: false,
          condition: { field: "device_shipping", value: true },
          options: [
            { value: "standard", label: "Standard (5-7 days)" },
            { value: "express", label: "Express (2-3 days)" },
            { value: "overnight", label: "Overnight" },
          ],
        },
      ],
    },
    {
      id: "additional",
      title: "Additional Notes",
      fields: [
        { id: "additional_software", type: "textarea", label: "Additional Software / Tools", required: false },
        { id: "special_instructions", type: "textarea", label: "Special Instructions", required: false },
      ],
    },
  ],
} as const;
